# Generated by Django 3.0.6 on 2020-06-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200601_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
